### ISSUE TITLE
hex_core does not return the body of an error message when an invalid semver is provided for revertion 

### ISSUE THREAD

**Issue by starbelly** [hexpm/hex_core#113]
If an invalid semver is provided as an argument when attempting to revert a package (i.e., "eh?") hexpm will return a 400 with an appropriate message (can only delete a release up to one hour after publication) however this message is not properly passed back to the caller. It's not clear as to why.  @wojtekmach believes the body is simply not passed back to the caller in this case. 

The raw error returned from hex_core: 

```erlang
{error,{rebar3_hex_revert,{api_error,<<"truecoat">>,<<"me">>,[72,84,84,80,32,115,116,97,116,117,115,32,99,111,100,101,58,32,"400"]
}}}
```

Or in other words : "HTTP status code: 400"

Edit:

Note this issue was originally opened on hexpm as https://github.com/hexpm/hexpm/issues/1015. If it turns out this a problem at in hexpm vs hex_core we can simply re-open the other, but my assumption is the same as @wojtekmach's on this one.

**Comment by wojtekmach** [comment]
Sorry, I didn’t remember off the top of my head. API functions are small wrappers around http and they return the full http response:

https://github.com/hexpm/hex_core/blob/v0.7.1/src/hex_api_release.erl#L132

So I think everything is fine in hex_core after all.

I’m assuming you’re using it through rebar3, could you make a request using hex core directly? If the response is missing details it’s likely server after all. But if response is good, it means that rebar3 integration is not showing the response body.

If it’s not server fault, could you also close the other hexpm issue? I believe you created two and looks like they have the same root cause.

**Comment by starbelly** [comment]
@wojtekmach Good point, let me double check that. I could have jumped the gun.

**Comment by starbelly** [comment]
@wojtekmach Indeed, I jumped the gun. Closing this and going to fix this in rebar3_hex 😁

**Comment by wojtekmach** [comment]
Thanks!
