### ISSUE TITLE
support setting a httpc profile

### ISSUE THREAD

**Issue by tsloughter** [hexpm/hex_core#33]
Rebar3 sets up an httpc profile for proxy settings and such and uses it in requests. It looks like hex_core has no support for setting a profile?

I think a good option would be to just add it to the config (using `default` by default) and then add the argument to the request call to `hex_httpc`. Does that sound good?

Should it just be named `http_profile` in the config? Or be more specific?

**Comment by wojtekmach** [comment]
> It looks like hex_core has no support for setting a profile?

Yes, the default `hex_http_httpc` adapter is a very thin wrapper around httpc. Our long term plan for mix integration is to use an Elixir http client (when it's done :D) so that's why it didn't get much love. I think allowing to pass profile makes sense but I'm not sure about calling it `http_profile` as other adapters may not have a notion of profile. How about:

```
#{
  http_adapter: hex_http_httpc,
  http_adapter_config: #{profile => default}
}
```

WDYT? Are there other https-specific things you'd like to pass to the adapter? cc @ericmj

**Comment by tsloughter** [comment]
Yea, that was my concern with the name. I think `http_adapter_config` sounds good.

I think the profile covers all the httpc-specific things we need to set.

**Comment by tsloughter** [comment]
Resolved by https://github.com/hexpm/hex_core/pull/36
